# Generated by Django 5.1 on 2024-09-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cuestionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(blank=True, related_name='cuestionarios', to='api.pregunta'),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_alternativa', models.TextField()),
                ('es_correcta', models.BooleanField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='api.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
