# Generated by Django 5.1 on 2024-09-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cuestionario_preguntas_alternativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='api.pregunta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto_respuesta', models.TextField()),
                ('es_correcta', models.BooleanField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
