# Generated by Django 5.1.1 on 2024-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cuestionario_preguntas_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='materia',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Fisica', 'Fisica'), ('Quimica', 'Quimica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='nivel',
            field=models.CharField(choices=[('1ero Medio', '1dro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ero Medio'), ('4to Medio', '4to Medio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='materia',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Fisica', 'Fisica'), ('Quimica', 'Quimica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('1ero Medio', '1dro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ero Medio'), ('4to Medio', '4to Medio')], max_length=10),
        ),
    ]
