# Generated by Django 5.1.1 on 2024-09-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cuestionario_materia_alter_cuestionario_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='materia',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Fisica', 'Fisica'), ('Quimica', 'Quimica'), ('Matematica', 'Matematica'), ('Lenguaje', 'Lenguaje')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='materia',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Fisica', 'Fisica'), ('Quimica', 'Quimica'), ('Matematica', 'Matematica'), ('Lenguaje', 'Lenguaje')], max_length=10),
        ),
    ]
