# Generated by Django 4.2.16 on 2024-10-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cuestionario_materia_alter_pregunta_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='es_correcta',
            field=models.BooleanField(null=True),
        ),
    ]
