# Generated by Django 4.2.16 on 2024-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_respuesta_es_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='nivel',
            field=models.CharField(choices=[('1ero Medio', '1dro Medio'), ('2do Medio', '2do Medio'), ('3ero Medio', '3ero Medio'), ('4to Medio', '4to Medio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.CharField(choices=[('1ero Medio', '1dro Medio'), ('2do Medio', '2do Medio'), ('3ero Medio', '3ero Medio'), ('4to Medio', '4to Medio')], max_length=10),
        ),
    ]
