# Generated by Django 4.2.16 on 2024-10-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cuestionario_nivel_alter_pregunta_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='materia',
            field=models.CharField(choices=[('Biologia', 'Biologia'), ('Fisica', 'Fisica'), ('Quimica', 'Quimica'), ('Matematica', 'Matematica'), ('Lenguaje', 'Lenguaje'), ('Historia', 'Historia')], max_length=10),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('conocimiento', models.ManyToManyField(to='api.conocimiento', verbose_name='Conocimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tema', models.ManyToManyField(to='api.tema', verbose_name='Temas')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tema', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materia', to='api.materia'),
        ),
    ]
